export const CarData = [
    {
        id: 0,
        image: "https://upload.wikimedia.org/wikipedia/commons/8/85/Porsche_911_Carrera_%287266826444%29.jpg",
        label: "Luxury",
        labelClass: "label--luxury",
        name: "Porsche 911 Carvarera",
        price: "250",
        transmission: "Auto",
        transmissionIcon: "fa-solid fa-gear",
        fuel: "Petrol",
        fuelIcon: "fa-solid fa-gas-pump",
        seats: "2",
        description: "Iconic rear-engine sports coupe with sharp handling and premium finish.",
        year: "2022",
        rating: "4.5",
        Reviews: "50",
        engine: "3.0L H6 Twin-Turbocharged",
        transmissionDetail: "7-Speed PDK Automatic",
        fuelEfficiency: "18 MPG Combined",
        seating: "2 Passengers",
        location: "Maroc Agadir" ,
        srclocation : "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d6883.611769591739!2d-9.5167628848736!3d30.38486953287851!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xdb3b6e9daad1cc9%3A0xbcf8d0b78bf48474!2sAgadir%2080000!5e0!3m2!1sfr!2sma!4v1774131787604!5m2!1sfr!2sma"
    },
    {
        id: 1,
        image: "https://upload.wikimedia.org/wikipedia/commons/2/28/2023_Tesla_Model_S_Plaid.jpg",
        label: "Electric",
        labelClass: "label--electric",
        name: "Tesla Model S Plaid",
        price: "180",
        transmission: "Auto",
        transmissionIcon: "fa-solid fa-gear",
        fuel: "Electric",
        fuelIcon: "fa-solid fa-bolt",
        seats: "5",
        description: "High-performance electric sedan with long range and cutting-edge tech.",
        year: "2023",
        rating: "2.5",
        Reviews: "10",
        engine: "Tri-Motor Electric AWD",
        transmissionDetail: "Single-Speed Automatic",
        fuelEfficiency: "120 MPGe Combined",
        seating: "5 Passengers"
    },
    {
        id: 2,
        image: "https://upload.wikimedia.org/wikipedia/commons/2/26/Land_Rover_Defender_110.jpg",
        label: "SUV",
        labelClass: "label--suv",
        name: "Land Rover Defender",
        price: "145",
        transmission: "Auto",
        transmissionIcon: "fa-solid fa-gear",
        fuel: "Diesel",
        fuelIcon: "fa-solid fa-gas-pump",
        seats: "7",
        description: "Rugged off-road SUV with spacious seating and durable build.",
        year: "2021",
        rating: "3",
        Reviews: "40",
        engine: "3.0L I6 Turbocharged Diesel",
        transmissionDetail: "8-Speed Automatic",
        fuelEfficiency: "22 MPG Combined",
        seating: "7 Passengers"
    },
    {
        id: 3,
        image: "https://upload.wikimedia.org/wikipedia/commons/9/97/BMW_5_Series.jpg",
        label: "Premium",
        labelClass: "label--premium",
        name: "BMW 5 Series",
        price: "110",
        transmission: "Auto",
        transmissionIcon: "fa-solid fa-gear",
        fuel: "Hybrid",
        fuelIcon: "fa-solid fa-leaf",
        seats: "5",
        description: "Executive sedan blending comfort, efficiency, and refined driving.",
        year: "2020",
        rating: "5",
        Reviews: "100",
        engine: "2.0L I4 Turbocharged Hybrid",
        transmissionDetail: "8-Speed Automatic",
        fuelEfficiency: "28 MPG Combined",
        seating: "5 Passengers"
    },
    {
        id: 4,
        image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Ford_Mustang_GT_%2837372750026%29.jpg",
        label: "Sport",
        labelClass: "label--sport",
        name: "Ford Mustang GT",
        price: "160",
        transmission: "Manual",
        transmissionIcon: "fa-solid fa-gear",
        fuel: "Petrol",
        fuelIcon: "fa-solid fa-gas-pump",
        seats: "4",
        description: "Muscle car with bold styling and engaging manual drive.",
        year: "2019",
        rating: "1.5",
        Reviews: "20",
        engine: "5.0L V8 Naturally Aspirated",
        transmissionDetail: "6-Speed Manual",
        fuelEfficiency: "16 MPG Combined",
        seating: "4 Passengers"
    },
    {
        id: 5,
        image: "https://upload.wikimedia.org/wikipedia/commons/a/ad/Audi_Q7_%284M%29_IMG_2692.jpg",
        label: "SUV",
        labelClass: "label--suv",
        name: "Audi Q7 Quattro",
        price: "130",
        transmission: "Auto",
        transmissionIcon: "fa-solid fa-gear",
        fuel: "Diesel",
        fuelIcon: "fa-solid fa-gas-pump",
        seats: "7",
        description: "Large luxury SUV with strong performance and family-ready space.",
        year: "2021",
        rating: "3",
        Reviews: "09",
        engine: "3.0L V6 Turbocharged Diesel",
        transmissionDetail: "8-Speed Automatic",
        fuelEfficiency: "23 MPG Combined",
        seating: "7 Passengers"
    }
];